[package]
name = "fairy"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
env_logger = "0.11.8"
gl33 = "0.2.1"
glfw = "0.59.0"
hecs = "0.10.5"
log = "0.4.27"
nalgebra = "0.33.2"
thiserror = "2.0.12"
